# Generated by Django 3.0.2 on 2020-01-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dono', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dono',
            name='endereco',
            field=models.CharField(default='Rua Tal', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dono',
            name='telefone_contato',
            field=models.CharField(default='9897866746', max_length=13),
            preserve_default=False,
        ),
    ]
